version: 2
jobs:
  prepare:
    docker:
      - image: mbedos/mbed-os-env:stable
    working_directory: ~
    steps:
      - checkout:
          path: mbed-os-ble-utils
      - run: |
          git clone https://github.com/ARMmbed/mbed-os.git
          git clone https://github.com/ARMmbed/mbed-os-example-ble.git
      - run:
          command: |
            cd mbed-os-example-ble
            for i in BLE_* ; do
              cd $i ;
              ln -s $PWD/../../mbed-os mbed-os ;
              mbed update ;
              rm -rf mbed-os-ble-utils ;
              ln -s $PWD/../../mbed-os-ble-utils mbed-os-ble-utils ;
              cd .. ;
            done
      - persist_to_workspace:
          root: /root/project
          paths:
            - mbed-os-example-ble
            - mbed-os-ble-utils
            - mbed-os

  build_nrf52840:
    docker:
      - image: mbedos/mbed-os-env:stable
    working_directory: ~
    steps:
      - attach_workspace:
          at: /root/project
      - run: |
          cd mbed-os-example-ble
          for i in BLE_* ; do cd $i ; mbed compile -t GCC_ARM -m NRF52840_DK || exit 1 ; cd .. ; done

  build_disco_l475vg:
    docker:
      - image: mbedos/mbed-os-env:stable
    working_directory: ~
    steps:
      - attach_workspace:
          at: /root/project
      - run: |
          cd mbed-os-example-ble
          for i in BLE_* ; do cd $i ; mbed compile -t GCC_ARM -m DISCO_L475VG_IOT01A || exit 1 ; cd .. ; done

workflows:
  version: 2
  workflow:
    jobs:
    - prepare
    - build_nrf52840:
        requires:
          - prepare
    - build_disco_l475vg:
        requires:
          - prepare
